### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by NC-MXTC** [JAPR98/NCTaskManager#1]
When checking the nextTimeAfter for a Task like `Task test = new Task("test", 5)` the method enters an infinite loop if executed like `test..nextTimeAfter(6)`
https://github.com/JAPR98/NCTaskManager/blob/233d278dc39d90c97e125ad3de5bc2c1e62a7d93/src/main/java/mx/edu/j2se/perez/tasks/Task.java#L189

**Comment by JAPR98** [comment]
Solved, thank you!!
